spring:
   application:
      name: trace-2
   zipkin:
      baseUrl: http://localhost:9411
   sleuth:
      sampler:
         percentage: 1
      
server:
   port: 9102
   
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:1001/eureka
         
