spring:
   application:
      name: config-server
   cloud:
      config:
         server:
            git:
               uri: https://github.com/xieyufish/spring-cloud-config-file
               #username: xieyufish
               #password: *****

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:1001/eureka
               
server:
   port: 1202